[package]
name = "high-bits-lwe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-primes = "0.3.0"
rug = "1.19.2"
hex = "0.4.3"
base64 = "0.20.0"
rand = "0.8.5"
